"""
35_bertopic_tables.py

VMP 2026-02-03

Generates supplementary LaTeX table for the selected BERTopic model (09__...)
and prints per-topic participant coverage.

Reads:
  ../data/public/bertopic/selection/overview/09__*__topic_overview.csv
  ../data/public/bertopic/selection/statement_topics/09__*__statement_topics.csv

Writes:
  ../fig/bertopic_mapping/BERTopic_overview.txt   (longtable of topics; supplementary section S1.6)

VMP 2026-02-08: tested and run.
VMP 2026-03-27: removed redundant phi/AUC table (now generated by 31_node_reliability.py);
                moved output from /fig/tables/ to /fig/bertopic_mapping/.
"""

import os
from pathlib import Path

import numpy as np
import pandas as pd

outpath = "../fig/bertopic_mapping"
os.makedirs(outpath, exist_ok=True)


# --- BERTopic topic overview table for the selected model (09__) ---
bertopic_path = "../data/public/bertopic/selection/overview/"
_matches = sorted(Path(bertopic_path).glob("09__*__topic_overview.csv"))
bertopic_df = pd.read_csv(_matches[0])


def _esc(s):
    if pd.isna(s):
        return ""
    s = str(s)
    for a, b in {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }.items():
        s = s.replace(a, b)
    return s


rep_cols = [c for c in ["RepDoc1", "RepDoc2", "RepDoc3"] if c in bertopic_df.columns]
d = bertopic_df[["Topic", "Count", "Keywords"] + rep_cols].copy()


def _join_reps(row):
    reps = [str(row[c]).strip() for c in rep_cols if pd.notna(row[c]) and str(row[c]).strip()]
    return ", ".join(reps)


d["Example"] = d.apply(_join_reps, axis=1)

# sort (keeps -1)
d["Topic_num"] = pd.to_numeric(d["Topic"], errors="coerce")
d = d.sort_values(["Topic_num", "Topic"], kind="mergesort").drop(columns="Topic_num")

# truncate to 5 keywords
d["Keywords"] = d["Keywords"].apply(
    lambda s: ", ".join(str(s).split(", ")[:5]) if pd.notna(s) else ""
)

# escape
d["Keywords"] = d["Keywords"].map(_esc)
d["Example"] = d["Example"].map(_esc)

lines = [
    r"\setlength{\LTleft}{0pt}",
    r"\setlength{\LTright}{0pt}",
    r"\setlength{\tabcolsep}{4pt}",
    r"\renewcommand{\arraystretch}{1.05}",
    r"\begingroup\small",
    r"\begin{longtable}{r r >{\raggedright\arraybackslash}p{0.44\textwidth} >{\raggedright\arraybackslash}p{0.44\textwidth}}",
    r"\toprule",
    r"Topic & n & Keywords & Representative Docs \\",
    r"\midrule",
    r"\endfirsthead",
    r"\toprule",
    r"Topic & n & Keywords & Representative Docs \\",
    r"\midrule",
    r"\endhead",
    r"\midrule",
    r"\multicolumn{4}{r}{Continued on next page} \\",
    r"\midrule",
    r"\endfoot",
    r"\bottomrule",
    r"\endlastfoot",
]
lines += [f"{r.Topic} & {r.Count} & {r.Keywords} & {r.Example} \\\\" for r in d.itertuples(index=False)]
lines += [r"\end{longtable}", r"\endgroup"]

outname = os.path.join(outpath, "BERTopic_overview.txt")
with open(outname, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print("Saved:", outname)


# --- Participant coverage per topic (model 09__, print only) ---
stmt_path = "../data/public/bertopic/selection/statement_topics/"
_stmt_matches = sorted(Path(stmt_path).glob("09__*__statement_topics.csv"))
stmt_df = pd.read_csv(_stmt_matches[0])

n_participants = stmt_df["key"].nunique()

coverage = (
    stmt_df[["key", "topic"]].drop_duplicates()
    .groupby("topic")["key"].count()
    .reset_index(name="n_participants")
)
coverage["pct_participants"] = coverage["n_participants"] / n_participants * 100

topic_labels = bertopic_df.rename(columns={"Topic": "topic", "Keywords": "keywords"})[["topic", "keywords"]]
coverage = coverage.merge(topic_labels, on="topic", how="left")
coverage = coverage.sort_values("topic").reset_index(drop=True)

print(f"\nN participants (across both waves): {n_participants}")
print(coverage[["topic", "keywords", "n_participants", "pct_participants"]].to_string(index=False))
